[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#115DCE"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"
