# spark/examples/spark-pi.yaml
#[첫 번째 분산 연산 실습] Spark Operator를 사용하여
#Driver 파드 1대와 Executor 파드 2대를 동적으로 띄우고,
#몬테카를로 알고리즘으로 원주율(Pi)을 분산 병렬 계산하는 SparkApplication


apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "docker.io/apache/spark:3.5.1"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 2              # 👈 2대의 Executor 파드가 분산 병렬 연산 수행!
    memory: "512m"
    labels:
      version: 3.5.1
